version: '3.3'
services:
  mongodb:
    image: mongo
    container_name: container-mongodb
    environment:
    - MONGO_DATA_DIR=./data/db
    - MONGO_LOG_DIR=./log
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
      - ./log:/log
